param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$OutputFile = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")).Path "book\knowledge\raw-notes.qmd")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$sourceDirs = Get-ChildItem -Path $RepoRoot -Directory |
    Where-Object { $_.Name -match '^\d{2}-' } |
    Sort-Object Name |
    Select-Object -ExpandProperty Name

function Convert-ObsidianMarkdown {
    param(
        [Parameter(Mandatory = $true)][string]$Text
    )

    # Convert Obsidian image wikilinks to standard relative Markdown image links.
    $converted = $Text -replace '!\[\[([^\]]+)\]\]', '![](../images/$1)'

    # Convert Obsidian page wikilinks to inline code labels to avoid broken links.
    $converted = $converted -replace '\[\[([^\]\|]+)(\|[^\]]+)?\]\]', '`$1`'

    return $converted
}

$bookKnowledgeDir = Join-Path $RepoRoot "book\knowledge"
if (-not (Test-Path $bookKnowledgeDir)) {
    New-Item -ItemType Directory -Path $bookKnowledgeDir -Force | Out-Null
}

$imageSourceDir = Join-Path $RepoRoot "images"
$imageTargetDir = Join-Path $RepoRoot "book\images"
if (Test-Path $imageSourceDir) {
    New-Item -ItemType Directory -Path $imageTargetDir -Force | Out-Null
    Get-ChildItem -Path $imageSourceDir -File | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination (Join-Path $imageTargetDir $_.Name) -Force
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$lines.Add("---")
$lines.Add("title: ""Appendix A Source Notes (Auto Synced)""")
$lines.Add("---")
$lines.Add("")
$lines.Add("This chapter is generated by `scripts/sync-notes-to-book.ps1`.")
$lines.Add("")
$lines.Add("Generated at: $timestamp")
$lines.Add("")
$lines.Add("Update Obsidian notes, rerun the script, and this appendix will refresh.")
$lines.Add("")

foreach ($dir in $sourceDirs) {
    $fullDir = Join-Path $RepoRoot $dir
    if (-not (Test-Path $fullDir)) {
        continue
    }

    $lines.Add("## $dir")
    $lines.Add("")

    $files = Get-ChildItem -Path $fullDir -Filter "*.md" -File | Sort-Object Name
    if (-not $files) {
        $lines.Add("No Markdown notes found in this directory.")
        $lines.Add("")
        continue
    }

    foreach ($file in $files) {
        $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        $relativePath = "$dir/$($file.Name)"
        $updatedAt = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm")

        $lines.Add("### $title")
        $lines.Add("")
        $lines.Add("- Source file: $relativePath")
        $lines.Add("- Last modified: $updatedAt")
        $lines.Add("")

        $rawText = Get-Content -Path $file.FullName -Raw -Encoding utf8
        $convertedText = Convert-ObsidianMarkdown -Text $rawText

        $trimmed = $convertedText.Trim()
        if ($trimmed.Length -gt 0) {
            $lines.AddRange($trimmed -split "`r?`n")
        } else {
            $lines.Add("(This note is currently empty.)")
        }
        $lines.Add("")
    }
}

[System.IO.File]::WriteAllLines($OutputFile, $lines, [System.Text.Encoding]::UTF8)
Write-Output "Synced notes to $OutputFile"
